/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module tilesort_2 (
    input clk,
    input up,
    input down,
    input left,
    input right,
    input center,
    output reg tile1_out,
    output reg tile2_out,
    output reg tile3_out,
    output reg tile4_out,
    output reg tile5_out,
    output reg tile6_out,
    output reg tile7_out,
    output reg tile8_out,
    output reg tile9_out,
    output reg tile10_out,
    output reg tile11_out,
    output reg tile12_out,
    output reg tile13_out,
    output reg tile14_out,
    output reg tile15_out,
    output reg tile16_out,
    output reg tile17_out,
    output reg tile18_out,
    output reg tile19_out,
    output reg tile20_out,
    output reg tile21_out,
    output reg tile22_out,
    output reg tile23_out,
    output reg tile24_out,
    output reg tile25_out,
    output reg selector_out,
    output reg debug1,
    output reg debug2,
    output reg debug3,
    output reg debug4
  );
  
  
  
  reg tile1_orientation;
  
  reg tile2_orientation;
  
  reg tile3_orientation;
  
  reg tile4_orientation;
  
  reg tile5_orientation;
  
  reg tile6_orientation;
  
  reg tile7_orientation;
  
  reg tile8_orientation;
  
  reg tile9_orientation;
  
  reg tile10_orientation;
  
  reg tile11_orientation;
  
  reg tile12_orientation;
  
  reg tile13_orientation;
  
  reg tile14_orientation;
  
  reg tile15_orientation;
  
  reg tile16_orientation;
  
  reg tile17_orientation;
  
  reg tile18_orientation;
  
  reg tile19_orientation;
  
  reg tile20_orientation;
  
  reg tile21_orientation;
  
  reg tile22_orientation;
  
  reg tile23_orientation;
  
  reg tile24_orientation;
  
  reg tile25_orientation;
  
  wire [1-1:0] M_selector_bitout;
  reg [10-1:0] M_selector_horizontaloffset;
  reg [9-1:0] M_selector_verticaloffset;
  selector_draw_4 selector (
    .clk(clk),
    .horizontaloffset(M_selector_horizontaloffset),
    .verticaloffset(M_selector_verticaloffset),
    .bitout(M_selector_bitout)
  );
  wire [1-1:0] M_tile1_bittodraw;
  reg [10-1:0] M_tile1_horizontaloffset;
  reg [9-1:0] M_tile1_verticaloffset;
  reg [3-1:0] M_tile1_shape;
  reg [3-1:0] M_tile1_orientation;
  tiledraw_5 tile1 (
    .clk(clk),
    .horizontaloffset(M_tile1_horizontaloffset),
    .verticaloffset(M_tile1_verticaloffset),
    .shape(M_tile1_shape),
    .orientation(M_tile1_orientation),
    .bittodraw(M_tile1_bittodraw)
  );
  wire [1-1:0] M_tile2_bittodraw;
  reg [10-1:0] M_tile2_horizontaloffset;
  reg [9-1:0] M_tile2_verticaloffset;
  reg [3-1:0] M_tile2_shape;
  reg [3-1:0] M_tile2_orientation;
  tiledraw_5 tile2 (
    .clk(clk),
    .horizontaloffset(M_tile2_horizontaloffset),
    .verticaloffset(M_tile2_verticaloffset),
    .shape(M_tile2_shape),
    .orientation(M_tile2_orientation),
    .bittodraw(M_tile2_bittodraw)
  );
  wire [1-1:0] M_tile3_bittodraw;
  reg [10-1:0] M_tile3_horizontaloffset;
  reg [9-1:0] M_tile3_verticaloffset;
  reg [3-1:0] M_tile3_shape;
  reg [3-1:0] M_tile3_orientation;
  tiledraw_5 tile3 (
    .clk(clk),
    .horizontaloffset(M_tile3_horizontaloffset),
    .verticaloffset(M_tile3_verticaloffset),
    .shape(M_tile3_shape),
    .orientation(M_tile3_orientation),
    .bittodraw(M_tile3_bittodraw)
  );
  wire [1-1:0] M_tile4_bittodraw;
  reg [10-1:0] M_tile4_horizontaloffset;
  reg [9-1:0] M_tile4_verticaloffset;
  reg [3-1:0] M_tile4_shape;
  reg [3-1:0] M_tile4_orientation;
  tiledraw_5 tile4 (
    .clk(clk),
    .horizontaloffset(M_tile4_horizontaloffset),
    .verticaloffset(M_tile4_verticaloffset),
    .shape(M_tile4_shape),
    .orientation(M_tile4_orientation),
    .bittodraw(M_tile4_bittodraw)
  );
  wire [1-1:0] M_tile5_bittodraw;
  reg [10-1:0] M_tile5_horizontaloffset;
  reg [9-1:0] M_tile5_verticaloffset;
  reg [3-1:0] M_tile5_shape;
  reg [3-1:0] M_tile5_orientation;
  tiledraw_5 tile5 (
    .clk(clk),
    .horizontaloffset(M_tile5_horizontaloffset),
    .verticaloffset(M_tile5_verticaloffset),
    .shape(M_tile5_shape),
    .orientation(M_tile5_orientation),
    .bittodraw(M_tile5_bittodraw)
  );
  wire [1-1:0] M_tile6_bittodraw;
  reg [10-1:0] M_tile6_horizontaloffset;
  reg [9-1:0] M_tile6_verticaloffset;
  reg [3-1:0] M_tile6_shape;
  reg [3-1:0] M_tile6_orientation;
  tiledraw_5 tile6 (
    .clk(clk),
    .horizontaloffset(M_tile6_horizontaloffset),
    .verticaloffset(M_tile6_verticaloffset),
    .shape(M_tile6_shape),
    .orientation(M_tile6_orientation),
    .bittodraw(M_tile6_bittodraw)
  );
  wire [1-1:0] M_tile7_bittodraw;
  reg [10-1:0] M_tile7_horizontaloffset;
  reg [9-1:0] M_tile7_verticaloffset;
  reg [3-1:0] M_tile7_shape;
  reg [3-1:0] M_tile7_orientation;
  tiledraw_5 tile7 (
    .clk(clk),
    .horizontaloffset(M_tile7_horizontaloffset),
    .verticaloffset(M_tile7_verticaloffset),
    .shape(M_tile7_shape),
    .orientation(M_tile7_orientation),
    .bittodraw(M_tile7_bittodraw)
  );
  wire [1-1:0] M_tile8_bittodraw;
  reg [10-1:0] M_tile8_horizontaloffset;
  reg [9-1:0] M_tile8_verticaloffset;
  reg [3-1:0] M_tile8_shape;
  reg [3-1:0] M_tile8_orientation;
  tiledraw_5 tile8 (
    .clk(clk),
    .horizontaloffset(M_tile8_horizontaloffset),
    .verticaloffset(M_tile8_verticaloffset),
    .shape(M_tile8_shape),
    .orientation(M_tile8_orientation),
    .bittodraw(M_tile8_bittodraw)
  );
  wire [1-1:0] M_tile9_bittodraw;
  reg [10-1:0] M_tile9_horizontaloffset;
  reg [9-1:0] M_tile9_verticaloffset;
  reg [3-1:0] M_tile9_shape;
  reg [3-1:0] M_tile9_orientation;
  tiledraw_5 tile9 (
    .clk(clk),
    .horizontaloffset(M_tile9_horizontaloffset),
    .verticaloffset(M_tile9_verticaloffset),
    .shape(M_tile9_shape),
    .orientation(M_tile9_orientation),
    .bittodraw(M_tile9_bittodraw)
  );
  wire [1-1:0] M_tile10_bittodraw;
  reg [10-1:0] M_tile10_horizontaloffset;
  reg [9-1:0] M_tile10_verticaloffset;
  reg [3-1:0] M_tile10_shape;
  reg [3-1:0] M_tile10_orientation;
  tiledraw_5 tile10 (
    .clk(clk),
    .horizontaloffset(M_tile10_horizontaloffset),
    .verticaloffset(M_tile10_verticaloffset),
    .shape(M_tile10_shape),
    .orientation(M_tile10_orientation),
    .bittodraw(M_tile10_bittodraw)
  );
  wire [1-1:0] M_tile11_bittodraw;
  reg [10-1:0] M_tile11_horizontaloffset;
  reg [9-1:0] M_tile11_verticaloffset;
  reg [3-1:0] M_tile11_shape;
  reg [3-1:0] M_tile11_orientation;
  tiledraw_5 tile11 (
    .clk(clk),
    .horizontaloffset(M_tile11_horizontaloffset),
    .verticaloffset(M_tile11_verticaloffset),
    .shape(M_tile11_shape),
    .orientation(M_tile11_orientation),
    .bittodraw(M_tile11_bittodraw)
  );
  wire [1-1:0] M_tile12_bittodraw;
  reg [10-1:0] M_tile12_horizontaloffset;
  reg [9-1:0] M_tile12_verticaloffset;
  reg [3-1:0] M_tile12_shape;
  reg [3-1:0] M_tile12_orientation;
  tiledraw_5 tile12 (
    .clk(clk),
    .horizontaloffset(M_tile12_horizontaloffset),
    .verticaloffset(M_tile12_verticaloffset),
    .shape(M_tile12_shape),
    .orientation(M_tile12_orientation),
    .bittodraw(M_tile12_bittodraw)
  );
  wire [1-1:0] M_tile13_bittodraw;
  reg [10-1:0] M_tile13_horizontaloffset;
  reg [9-1:0] M_tile13_verticaloffset;
  reg [3-1:0] M_tile13_shape;
  reg [3-1:0] M_tile13_orientation;
  tiledraw_5 tile13 (
    .clk(clk),
    .horizontaloffset(M_tile13_horizontaloffset),
    .verticaloffset(M_tile13_verticaloffset),
    .shape(M_tile13_shape),
    .orientation(M_tile13_orientation),
    .bittodraw(M_tile13_bittodraw)
  );
  wire [1-1:0] M_tile14_bittodraw;
  reg [10-1:0] M_tile14_horizontaloffset;
  reg [9-1:0] M_tile14_verticaloffset;
  reg [3-1:0] M_tile14_shape;
  reg [3-1:0] M_tile14_orientation;
  tiledraw_5 tile14 (
    .clk(clk),
    .horizontaloffset(M_tile14_horizontaloffset),
    .verticaloffset(M_tile14_verticaloffset),
    .shape(M_tile14_shape),
    .orientation(M_tile14_orientation),
    .bittodraw(M_tile14_bittodraw)
  );
  wire [1-1:0] M_tile15_bittodraw;
  reg [10-1:0] M_tile15_horizontaloffset;
  reg [9-1:0] M_tile15_verticaloffset;
  reg [3-1:0] M_tile15_shape;
  reg [3-1:0] M_tile15_orientation;
  tiledraw_5 tile15 (
    .clk(clk),
    .horizontaloffset(M_tile15_horizontaloffset),
    .verticaloffset(M_tile15_verticaloffset),
    .shape(M_tile15_shape),
    .orientation(M_tile15_orientation),
    .bittodraw(M_tile15_bittodraw)
  );
  wire [1-1:0] M_tile16_bittodraw;
  reg [10-1:0] M_tile16_horizontaloffset;
  reg [9-1:0] M_tile16_verticaloffset;
  reg [3-1:0] M_tile16_shape;
  reg [3-1:0] M_tile16_orientation;
  tiledraw_5 tile16 (
    .clk(clk),
    .horizontaloffset(M_tile16_horizontaloffset),
    .verticaloffset(M_tile16_verticaloffset),
    .shape(M_tile16_shape),
    .orientation(M_tile16_orientation),
    .bittodraw(M_tile16_bittodraw)
  );
  wire [1-1:0] M_tile17_bittodraw;
  reg [10-1:0] M_tile17_horizontaloffset;
  reg [9-1:0] M_tile17_verticaloffset;
  reg [3-1:0] M_tile17_shape;
  reg [3-1:0] M_tile17_orientation;
  tiledraw_5 tile17 (
    .clk(clk),
    .horizontaloffset(M_tile17_horizontaloffset),
    .verticaloffset(M_tile17_verticaloffset),
    .shape(M_tile17_shape),
    .orientation(M_tile17_orientation),
    .bittodraw(M_tile17_bittodraw)
  );
  wire [1-1:0] M_tile18_bittodraw;
  reg [10-1:0] M_tile18_horizontaloffset;
  reg [9-1:0] M_tile18_verticaloffset;
  reg [3-1:0] M_tile18_shape;
  reg [3-1:0] M_tile18_orientation;
  tiledraw_5 tile18 (
    .clk(clk),
    .horizontaloffset(M_tile18_horizontaloffset),
    .verticaloffset(M_tile18_verticaloffset),
    .shape(M_tile18_shape),
    .orientation(M_tile18_orientation),
    .bittodraw(M_tile18_bittodraw)
  );
  wire [1-1:0] M_tile19_bittodraw;
  reg [10-1:0] M_tile19_horizontaloffset;
  reg [9-1:0] M_tile19_verticaloffset;
  reg [3-1:0] M_tile19_shape;
  reg [3-1:0] M_tile19_orientation;
  tiledraw_5 tile19 (
    .clk(clk),
    .horizontaloffset(M_tile19_horizontaloffset),
    .verticaloffset(M_tile19_verticaloffset),
    .shape(M_tile19_shape),
    .orientation(M_tile19_orientation),
    .bittodraw(M_tile19_bittodraw)
  );
  wire [1-1:0] M_tile20_bittodraw;
  reg [10-1:0] M_tile20_horizontaloffset;
  reg [9-1:0] M_tile20_verticaloffset;
  reg [3-1:0] M_tile20_shape;
  reg [3-1:0] M_tile20_orientation;
  tiledraw_5 tile20 (
    .clk(clk),
    .horizontaloffset(M_tile20_horizontaloffset),
    .verticaloffset(M_tile20_verticaloffset),
    .shape(M_tile20_shape),
    .orientation(M_tile20_orientation),
    .bittodraw(M_tile20_bittodraw)
  );
  wire [1-1:0] M_tile21_bittodraw;
  reg [10-1:0] M_tile21_horizontaloffset;
  reg [9-1:0] M_tile21_verticaloffset;
  reg [3-1:0] M_tile21_shape;
  reg [3-1:0] M_tile21_orientation;
  tiledraw_5 tile21 (
    .clk(clk),
    .horizontaloffset(M_tile21_horizontaloffset),
    .verticaloffset(M_tile21_verticaloffset),
    .shape(M_tile21_shape),
    .orientation(M_tile21_orientation),
    .bittodraw(M_tile21_bittodraw)
  );
  wire [1-1:0] M_tile22_bittodraw;
  reg [10-1:0] M_tile22_horizontaloffset;
  reg [9-1:0] M_tile22_verticaloffset;
  reg [3-1:0] M_tile22_shape;
  reg [3-1:0] M_tile22_orientation;
  tiledraw_5 tile22 (
    .clk(clk),
    .horizontaloffset(M_tile22_horizontaloffset),
    .verticaloffset(M_tile22_verticaloffset),
    .shape(M_tile22_shape),
    .orientation(M_tile22_orientation),
    .bittodraw(M_tile22_bittodraw)
  );
  wire [1-1:0] M_tile23_bittodraw;
  reg [10-1:0] M_tile23_horizontaloffset;
  reg [9-1:0] M_tile23_verticaloffset;
  reg [3-1:0] M_tile23_shape;
  reg [3-1:0] M_tile23_orientation;
  tiledraw_5 tile23 (
    .clk(clk),
    .horizontaloffset(M_tile23_horizontaloffset),
    .verticaloffset(M_tile23_verticaloffset),
    .shape(M_tile23_shape),
    .orientation(M_tile23_orientation),
    .bittodraw(M_tile23_bittodraw)
  );
  wire [1-1:0] M_tile24_bittodraw;
  reg [10-1:0] M_tile24_horizontaloffset;
  reg [9-1:0] M_tile24_verticaloffset;
  reg [3-1:0] M_tile24_shape;
  reg [3-1:0] M_tile24_orientation;
  tiledraw_5 tile24 (
    .clk(clk),
    .horizontaloffset(M_tile24_horizontaloffset),
    .verticaloffset(M_tile24_verticaloffset),
    .shape(M_tile24_shape),
    .orientation(M_tile24_orientation),
    .bittodraw(M_tile24_bittodraw)
  );
  wire [1-1:0] M_tile25_bittodraw;
  reg [10-1:0] M_tile25_horizontaloffset;
  reg [9-1:0] M_tile25_verticaloffset;
  reg [3-1:0] M_tile25_shape;
  reg [3-1:0] M_tile25_orientation;
  tiledraw_5 tile25 (
    .clk(clk),
    .horizontaloffset(M_tile25_horizontaloffset),
    .verticaloffset(M_tile25_verticaloffset),
    .shape(M_tile25_shape),
    .orientation(M_tile25_orientation),
    .bittodraw(M_tile25_bittodraw)
  );
  localparam S1_selected_tile = 5'd0;
  localparam S2_selected_tile = 5'd1;
  localparam S3_selected_tile = 5'd2;
  localparam S4_selected_tile = 5'd3;
  localparam S5_selected_tile = 5'd4;
  localparam S6_selected_tile = 5'd5;
  localparam S7_selected_tile = 5'd6;
  localparam S8_selected_tile = 5'd7;
  localparam S9_selected_tile = 5'd8;
  localparam S10_selected_tile = 5'd9;
  localparam S11_selected_tile = 5'd10;
  localparam S12_selected_tile = 5'd11;
  localparam S13_selected_tile = 5'd12;
  localparam S14_selected_tile = 5'd13;
  localparam S15_selected_tile = 5'd14;
  localparam S16_selected_tile = 5'd15;
  localparam S17_selected_tile = 5'd16;
  localparam S18_selected_tile = 5'd17;
  localparam S19_selected_tile = 5'd18;
  localparam S20_selected_tile = 5'd19;
  localparam S21_selected_tile = 5'd20;
  localparam S22_selected_tile = 5'd21;
  localparam S23_selected_tile = 5'd22;
  localparam S24_selected_tile = 5'd23;
  localparam S25_selected_tile = 5'd24;
  
  reg [4:0] M_selected_tile_d, M_selected_tile_q = S1_selected_tile;
  
  always @* begin
    M_selected_tile_d = M_selected_tile_q;
    
    debug1 = 1'h0;
    debug2 = 1'h0;
    debug3 = 1'h0;
    debug4 = 1'h0;
    M_selector_horizontaloffset = 1'h0;
    M_selector_verticaloffset = 1'h0;
    selector_out = M_selector_bitout;
    
    case (M_selected_tile_q)
      S1_selected_tile: begin
        M_selector_horizontaloffset = 1'h0;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          tile1_orientation = tile1_orientation + 1'h1;
          M_tile1_orientation = tile1_orientation;
        end
        if (left) begin
          M_selected_tile_d = S25_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S2_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S21_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S6_selected_tile;
          debug1 = 1'h1;
        end
      end
      S2_selected_tile: begin
        M_selector_horizontaloffset = 7'h78;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          tile2_orientation = tile2_orientation + 1'h1;
          M_tile2_orientation = tile2_orientation;
        end
        if (left) begin
          M_selected_tile_d = S1_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S3_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S22_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S7_selected_tile;
          debug1 = 1'h1;
        end
      end
      S3_selected_tile: begin
        M_selector_horizontaloffset = 8'hf0;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          tile3_orientation = tile3_orientation + 1'h1;
          M_tile3_orientation = tile3_orientation;
        end
        if (left) begin
          M_selected_tile_d = S2_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S4_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S23_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S8_selected_tile;
          debug1 = 1'h1;
        end
      end
      S4_selected_tile: begin
        M_selector_horizontaloffset = 9'h168;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          tile4_orientation = tile4_orientation + 1'h1;
          M_tile4_orientation = tile4_orientation;
        end
        if (left) begin
          M_selected_tile_d = S3_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S5_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S24_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S9_selected_tile;
          debug1 = 1'h1;
        end
      end
      S5_selected_tile: begin
        M_selector_horizontaloffset = 9'h1e0;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          tile5_orientation = tile5_orientation + 1'h1;
          M_tile5_orientation = tile5_orientation;
        end
        if (left) begin
          M_selected_tile_d = S4_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S6_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S25_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S10_selected_tile;
          debug1 = 1'h1;
        end
      end
      S6_selected_tile: begin
        M_selector_horizontaloffset = 6'h3c;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          tile6_orientation = tile6_orientation + 1'h1;
          M_tile6_orientation = tile6_orientation;
        end
        if (left) begin
          M_selected_tile_d = S5_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S7_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S1_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S11_selected_tile;
          debug1 = 1'h1;
        end
      end
      S7_selected_tile: begin
        M_selector_horizontaloffset = 8'hb4;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          tile7_orientation = tile7_orientation + 1'h1;
          M_tile7_orientation = tile7_orientation;
        end
        if (left) begin
          M_selected_tile_d = S6_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S8_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S2_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S12_selected_tile;
          debug1 = 1'h1;
        end
      end
      S8_selected_tile: begin
        M_selector_horizontaloffset = 9'h12c;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          tile8_orientation = tile8_orientation + 1'h1;
          M_tile8_orientation = tile8_orientation;
        end
        if (left) begin
          M_selected_tile_d = S7_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S9_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S3_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S13_selected_tile;
          debug1 = 1'h1;
        end
      end
      S9_selected_tile: begin
        M_selector_horizontaloffset = 9'h1a4;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          tile9_orientation = tile9_orientation + 1'h1;
          M_tile9_orientation = tile9_orientation;
        end
        if (left) begin
          M_selected_tile_d = S8_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S10_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S4_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S14_selected_tile;
          debug1 = 1'h1;
        end
      end
      S10_selected_tile: begin
        M_selector_horizontaloffset = 10'h21c;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          tile10_orientation = tile10_orientation + 1'h1;
          M_tile10_orientation = tile10_orientation;
        end
        if (left) begin
          M_selected_tile_d = S9_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S11_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S5_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S15_selected_tile;
          debug1 = 1'h1;
        end
      end
      S11_selected_tile: begin
        M_selector_horizontaloffset = 1'h0;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          tile11_orientation = tile11_orientation + 1'h1;
          M_tile11_orientation = tile11_orientation;
        end
        if (left) begin
          M_selected_tile_d = S10_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S12_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S6_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S16_selected_tile;
          debug1 = 1'h1;
        end
      end
      S12_selected_tile: begin
        M_selector_horizontaloffset = 7'h78;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          tile12_orientation = tile12_orientation + 1'h1;
          M_tile12_orientation = tile12_orientation;
        end
        if (left) begin
          M_selected_tile_d = S11_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S13_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S7_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S17_selected_tile;
          debug1 = 1'h1;
        end
      end
      S13_selected_tile: begin
        M_selector_horizontaloffset = 8'hf0;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          tile13_orientation = tile13_orientation + 1'h1;
          M_tile13_orientation = tile13_orientation;
        end
        if (left) begin
          M_selected_tile_d = S12_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S14_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S8_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S18_selected_tile;
          debug1 = 1'h1;
        end
      end
      S14_selected_tile: begin
        M_selector_horizontaloffset = 9'h168;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          tile14_orientation = tile14_orientation + 1'h1;
          M_tile14_orientation = tile14_orientation;
        end
        if (left) begin
          M_selected_tile_d = S13_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S15_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S9_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S19_selected_tile;
          debug1 = 1'h1;
        end
      end
      S15_selected_tile: begin
        M_selector_horizontaloffset = 9'h1e0;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          tile15_orientation = tile15_orientation + 1'h1;
          M_tile15_orientation = tile15_orientation;
        end
        if (left) begin
          M_selected_tile_d = S14_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S16_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S10_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S20_selected_tile;
          debug1 = 1'h1;
        end
      end
      S16_selected_tile: begin
        M_selector_horizontaloffset = 6'h3c;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          tile16_orientation = tile16_orientation + 1'h1;
          M_tile16_orientation = tile16_orientation;
        end
        if (left) begin
          M_selected_tile_d = S15_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S17_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S11_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S21_selected_tile;
          debug1 = 1'h1;
        end
      end
      S17_selected_tile: begin
        M_selector_horizontaloffset = 8'hb4;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          tile17_orientation = tile17_orientation + 1'h1;
          M_tile17_orientation = tile17_orientation;
        end
        if (left) begin
          M_selected_tile_d = S16_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S18_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S12_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S22_selected_tile;
          debug1 = 1'h1;
        end
      end
      S18_selected_tile: begin
        M_selector_horizontaloffset = 9'h12c;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          tile18_orientation = tile18_orientation + 1'h1;
          M_tile18_orientation = tile18_orientation;
        end
        if (left) begin
          M_selected_tile_d = S17_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S19_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S13_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S23_selected_tile;
          debug1 = 1'h1;
        end
      end
      S19_selected_tile: begin
        M_selector_horizontaloffset = 9'h1a4;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          tile19_orientation = tile19_orientation + 1'h1;
          M_tile19_orientation = tile19_orientation;
        end
        if (left) begin
          M_selected_tile_d = S18_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S20_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S14_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S24_selected_tile;
          debug1 = 1'h1;
        end
      end
      S20_selected_tile: begin
        M_selector_horizontaloffset = 10'h21c;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          tile20_orientation = tile20_orientation + 1'h1;
          M_tile20_orientation = tile20_orientation;
        end
        if (left) begin
          M_selected_tile_d = S19_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S21_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S15_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S25_selected_tile;
          debug1 = 1'h1;
        end
      end
      S21_selected_tile: begin
        M_selector_horizontaloffset = 1'h0;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          tile21_orientation = tile21_orientation + 1'h1;
          M_tile21_orientation = tile21_orientation;
        end
        if (left) begin
          M_selected_tile_d = S20_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S22_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S16_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S1_selected_tile;
          debug1 = 1'h1;
        end
      end
      S22_selected_tile: begin
        M_selector_horizontaloffset = 7'h78;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          tile22_orientation = tile22_orientation + 1'h1;
          M_tile22_orientation = tile22_orientation;
        end
        if (left) begin
          M_selected_tile_d = S21_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S23_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S17_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S2_selected_tile;
          debug1 = 1'h1;
        end
      end
      S23_selected_tile: begin
        M_selector_horizontaloffset = 8'hf0;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          tile23_orientation = tile23_orientation + 1'h1;
          M_tile23_orientation = tile23_orientation;
        end
        if (left) begin
          M_selected_tile_d = S22_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S24_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S18_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S3_selected_tile;
          debug1 = 1'h1;
        end
      end
      S24_selected_tile: begin
        M_selector_horizontaloffset = 9'h168;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          tile24_orientation = tile24_orientation + 1'h1;
          M_tile24_orientation = tile24_orientation;
        end
        if (left) begin
          M_selected_tile_d = S23_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S25_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S19_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S4_selected_tile;
          debug1 = 1'h1;
        end
      end
      S25_selected_tile: begin
        M_selector_horizontaloffset = 9'h1e0;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          tile25_orientation = tile25_orientation + 1'h1;
          M_tile25_orientation = tile25_orientation;
        end
        if (left) begin
          M_selected_tile_d = S24_selected_tile;
          debug1 = 1'h1;
        end
        if (right) begin
          M_selected_tile_d = S1_selected_tile;
          debug1 = 1'h1;
        end
        if (up) begin
          M_selected_tile_d = S20_selected_tile;
          debug1 = 1'h1;
        end
        if (down) begin
          M_selected_tile_d = S5_selected_tile;
          debug1 = 1'h1;
        end
      end
    endcase
    M_tile1_horizontaloffset = 1'h0;
    M_tile1_verticaloffset = 1'h0;
    M_tile1_shape = 1'h0;
    M_tile1_orientation = 1'h0;
    tile1_out = M_tile1_bittodraw;
    M_tile2_horizontaloffset = 7'h78;
    M_tile2_verticaloffset = 1'h0;
    M_tile2_shape = 1'h0;
    M_tile2_orientation = 1'h0;
    tile2_out = M_tile2_bittodraw;
    M_tile3_horizontaloffset = 8'hf0;
    M_tile3_verticaloffset = 1'h0;
    M_tile3_shape = 1'h0;
    M_tile3_orientation = 1'h0;
    tile3_out = M_tile3_bittodraw;
    M_tile4_horizontaloffset = 9'h168;
    M_tile4_verticaloffset = 1'h0;
    M_tile4_shape = 1'h0;
    M_tile4_orientation = 1'h0;
    tile4_out = M_tile4_bittodraw;
    M_tile5_horizontaloffset = 9'h1e0;
    M_tile5_verticaloffset = 1'h0;
    M_tile5_shape = 1'h0;
    M_tile5_orientation = 1'h0;
    tile5_out = M_tile5_bittodraw;
    M_tile6_horizontaloffset = 6'h3c;
    M_tile6_verticaloffset = 6'h34;
    M_tile6_shape = 1'h0;
    M_tile6_orientation = 1'h0;
    tile6_out = M_tile6_bittodraw;
    M_tile7_horizontaloffset = 8'hb4;
    M_tile7_verticaloffset = 6'h34;
    M_tile7_shape = 1'h1;
    M_tile7_orientation = 1'h0;
    tile7_out = M_tile7_bittodraw;
    M_tile8_horizontaloffset = 9'h12c;
    M_tile8_verticaloffset = 6'h34;
    M_tile8_shape = 1'h1;
    M_tile8_orientation = 1'h0;
    tile8_out = M_tile8_bittodraw;
    M_tile9_horizontaloffset = 9'h1a4;
    M_tile9_verticaloffset = 6'h34;
    M_tile9_shape = 1'h0;
    M_tile9_orientation = 1'h0;
    tile9_out = M_tile9_bittodraw;
    M_tile10_horizontaloffset = 10'h21c;
    M_tile10_verticaloffset = 6'h34;
    M_tile10_shape = 1'h1;
    M_tile10_orientation = 1'h0;
    tile10_out = M_tile10_bittodraw;
    M_tile11_horizontaloffset = 1'h0;
    M_tile11_verticaloffset = 7'h68;
    M_tile11_shape = 1'h1;
    M_tile11_orientation = 1'h0;
    tile11_out = M_tile11_bittodraw;
    M_tile12_horizontaloffset = 7'h78;
    M_tile12_verticaloffset = 7'h68;
    M_tile12_shape = 2'h2;
    M_tile12_orientation = 1'h0;
    tile12_out = M_tile12_bittodraw;
    M_tile13_horizontaloffset = 8'hf0;
    M_tile13_verticaloffset = 7'h68;
    M_tile13_shape = 1'h0;
    M_tile13_orientation = 1'h0;
    tile13_out = M_tile13_bittodraw;
    M_tile14_horizontaloffset = 9'h168;
    M_tile14_verticaloffset = 7'h68;
    M_tile14_shape = 1'h1;
    M_tile14_orientation = 1'h0;
    tile14_out = M_tile14_bittodraw;
    M_tile15_horizontaloffset = 9'h1e0;
    M_tile15_verticaloffset = 7'h68;
    M_tile15_shape = 1'h0;
    M_tile15_orientation = 1'h0;
    tile15_out = M_tile15_bittodraw;
    M_tile16_horizontaloffset = 6'h3c;
    M_tile16_verticaloffset = 8'h9c;
    M_tile16_shape = 1'h0;
    M_tile16_orientation = 1'h0;
    tile16_out = M_tile16_bittodraw;
    M_tile17_horizontaloffset = 8'hb4;
    M_tile17_verticaloffset = 8'h9c;
    M_tile17_shape = 2'h2;
    M_tile17_orientation = 1'h0;
    tile17_out = M_tile17_bittodraw;
    M_tile18_horizontaloffset = 9'h12c;
    M_tile18_verticaloffset = 8'h9c;
    M_tile18_shape = 2'h2;
    M_tile18_orientation = 1'h0;
    tile18_out = M_tile18_bittodraw;
    M_tile19_horizontaloffset = 9'h1a4;
    M_tile19_verticaloffset = 8'h9c;
    M_tile19_shape = 1'h1;
    M_tile19_orientation = 1'h0;
    tile19_out = M_tile19_bittodraw;
    M_tile20_horizontaloffset = 10'h21c;
    M_tile20_verticaloffset = 8'h9c;
    M_tile20_shape = 1'h0;
    M_tile20_orientation = 1'h0;
    tile20_out = M_tile20_bittodraw;
    M_tile21_horizontaloffset = 1'h0;
    M_tile21_verticaloffset = 8'hd0;
    M_tile21_shape = 1'h0;
    M_tile21_orientation = 1'h0;
    tile21_out = M_tile21_bittodraw;
    M_tile22_horizontaloffset = 7'h78;
    M_tile22_verticaloffset = 8'hd0;
    M_tile22_shape = 1'h1;
    M_tile22_orientation = 1'h0;
    tile22_out = M_tile22_bittodraw;
    M_tile23_horizontaloffset = 8'hf0;
    M_tile23_verticaloffset = 8'hd0;
    M_tile23_shape = 1'h1;
    M_tile23_orientation = 1'h0;
    tile23_out = M_tile23_bittodraw;
    M_tile24_horizontaloffset = 9'h168;
    M_tile24_verticaloffset = 8'hd0;
    M_tile24_shape = 1'h0;
    M_tile24_orientation = 1'h0;
    tile24_out = M_tile24_bittodraw;
    M_tile25_horizontaloffset = 9'h1e0;
    M_tile25_verticaloffset = 8'hd0;
    M_tile25_shape = 2'h2;
    M_tile25_orientation = 1'h0;
    tile25_out = M_tile25_bittodraw;
  end
  
  always @(posedge clk) begin
    M_selected_tile_q <= M_selected_tile_d;
  end
  
endmodule
