/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module draw_tile_6 (
    input clk,
    input [9:0] horizontaloffset,
    input [8:0] verticaloffset,
    input [50:0] fullcounter,
    output reg address,
    output reg draw
  );
  
  
  
  wire [1-1:0] M_hvsync_vga_h_sync;
  wire [1-1:0] M_hvsync_vga_v_sync;
  wire [1-1:0] M_hvsync_inDisplayArea;
  wire [11-1:0] M_hvsync_CounterX;
  wire [9-1:0] M_hvsync_CounterY;
  hvsync_generator_1 hvsync (
    .clk(clk),
    .vga_h_sync(M_hvsync_vga_h_sync),
    .vga_v_sync(M_hvsync_vga_v_sync),
    .inDisplayArea(M_hvsync_inDisplayArea),
    .CounterX(M_hvsync_CounterX),
    .CounterY(M_hvsync_CounterY)
  );
  
  reg [10:0] counterh;
  
  reg [8:0] counterv;
  
  always @* begin
    counterh = M_hvsync_CounterX;
    counterv = M_hvsync_CounterY;
    if (((counterh >= 9'h177 + horizontaloffset & counterh <= 9'h1dd + horizontaloffset)) & ((counterv >= 7'h78 + verticaloffset) & (counterv <= 8'hb4 + verticaloffset))) begin
      address = counterv - verticaloffset - 7'h78;
      draw = fullcounter[(6'h33 - ((counterh - 9'h177 - horizontaloffset) / 2'h2))*1+0-:1];
    end else begin
      draw = 1'h0;
      address = 10'h3e7;
    end
  end
endmodule
