/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module tilesort_2 (
    input clk,
    input up,
    input down,
    input left,
    input right,
    input center,
    output reg shape0_out,
    output reg selector_out,
    output reg debug1,
    output reg debug2,
    output reg debug3,
    output reg debug4
  );
  
  
  
  wire [1-1:0] M_selector_bitout;
  reg [10-1:0] M_selector_horizontaloffset;
  reg [9-1:0] M_selector_verticaloffset;
  selector_draw_4 selector (
    .clk(clk),
    .horizontaloffset(M_selector_horizontaloffset),
    .verticaloffset(M_selector_verticaloffset),
    .bitout(M_selector_bitout)
  );
  wire [1-1:0] M_counter_inc_state;
  stateCounter_5 counter (
    .clk(clk),
    .inc_state(M_counter_inc_state)
  );
  wire [1-1:0] M_shape0_bitout;
  reg [10-1:0] M_shape0_horizontaloffset;
  reg [9-1:0] M_shape0_verticaloffset;
  reg [3-1:0] M_shape0_orientation;
  shape0draw_6 shape0 (
    .clk(clk),
    .horizontaloffset(M_shape0_horizontaloffset),
    .verticaloffset(M_shape0_verticaloffset),
    .orientation(M_shape0_orientation),
    .bitout(M_shape0_bitout)
  );
  localparam S1_selected_tile = 5'd0;
  localparam S2_selected_tile = 5'd1;
  localparam S3_selected_tile = 5'd2;
  localparam S4_selected_tile = 5'd3;
  localparam S5_selected_tile = 5'd4;
  localparam S6_selected_tile = 5'd5;
  localparam S7_selected_tile = 5'd6;
  localparam S8_selected_tile = 5'd7;
  localparam S9_selected_tile = 5'd8;
  localparam S10_selected_tile = 5'd9;
  localparam S11_selected_tile = 5'd10;
  localparam S12_selected_tile = 5'd11;
  localparam S13_selected_tile = 5'd12;
  localparam S14_selected_tile = 5'd13;
  localparam S15_selected_tile = 5'd14;
  localparam S16_selected_tile = 5'd15;
  localparam S17_selected_tile = 5'd16;
  localparam S18_selected_tile = 5'd17;
  localparam S19_selected_tile = 5'd18;
  localparam S20_selected_tile = 5'd19;
  localparam S21_selected_tile = 5'd20;
  localparam S22_selected_tile = 5'd21;
  localparam S23_selected_tile = 5'd22;
  localparam S24_selected_tile = 5'd23;
  localparam S25_selected_tile = 5'd24;
  
  reg [4:0] M_selected_tile_d, M_selected_tile_q = S1_selected_tile;
  reg [2:0] M_tile1_orientation_d, M_tile1_orientation_q = 1'h0;
  
  always @* begin
    M_selected_tile_d = M_selected_tile_q;
    M_tile1_orientation_d = M_tile1_orientation_q;
    
    debug1 = 1'h0;
    debug2 = 1'h0;
    debug3 = 1'h0;
    debug4 = 1'h0;
    M_selector_horizontaloffset = 1'h0;
    M_selector_verticaloffset = 1'h0;
    selector_out = M_selector_bitout;
    M_shape0_horizontaloffset = 1'h0;
    M_shape0_verticaloffset = 1'h0;
    if (M_tile1_orientation_q > 3'h5) begin
      M_tile1_orientation_d = 1'h0;
    end else begin
      if (M_tile1_orientation_q < 1'h0) begin
        M_tile1_orientation_d = 3'h5;
      end
    end
    M_shape0_orientation = M_tile1_orientation_q;
    shape0_out = M_shape0_bitout;
    
    case (M_selected_tile_q)
      S1_selected_tile: begin
        M_selector_horizontaloffset = 1'h0;
        M_selector_verticaloffset = 1'h0;
        if (center & M_counter_inc_state) begin
          M_tile1_orientation_d = M_tile1_orientation_q + 1'h1;
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S25_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S2_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S21_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S6_selected_tile;
          debug1 = 1'h1;
        end
      end
      S2_selected_tile: begin
        M_selector_horizontaloffset = 7'h78;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S1_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S3_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S22_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S7_selected_tile;
          debug1 = 1'h1;
        end
      end
      S3_selected_tile: begin
        M_selector_horizontaloffset = 8'hf0;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S2_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S4_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S23_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S8_selected_tile;
          debug1 = 1'h1;
        end
      end
      S4_selected_tile: begin
        M_selector_horizontaloffset = 9'h168;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S3_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S5_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S24_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S9_selected_tile;
          debug1 = 1'h1;
        end
      end
      S5_selected_tile: begin
        M_selector_horizontaloffset = 9'h1e0;
        M_selector_verticaloffset = 1'h0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S4_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S6_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S25_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S10_selected_tile;
          debug1 = 1'h1;
        end
      end
      S6_selected_tile: begin
        M_selector_horizontaloffset = 6'h3c;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S5_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S7_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S1_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S11_selected_tile;
          debug1 = 1'h1;
        end
      end
      S7_selected_tile: begin
        M_selector_horizontaloffset = 8'hb4;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S6_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S8_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S2_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S12_selected_tile;
          debug1 = 1'h1;
        end
      end
      S8_selected_tile: begin
        M_selector_horizontaloffset = 9'h12c;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S7_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S9_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S3_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S13_selected_tile;
          debug1 = 1'h1;
        end
      end
      S9_selected_tile: begin
        M_selector_horizontaloffset = 9'h1a4;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S8_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S10_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S4_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S14_selected_tile;
          debug1 = 1'h1;
        end
      end
      S10_selected_tile: begin
        M_selector_horizontaloffset = 10'h21c;
        M_selector_verticaloffset = 6'h34;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S9_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S11_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S5_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S15_selected_tile;
          debug1 = 1'h1;
        end
      end
      S11_selected_tile: begin
        M_selector_horizontaloffset = 1'h0;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S10_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S12_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S6_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S16_selected_tile;
          debug1 = 1'h1;
        end
      end
      S12_selected_tile: begin
        M_selector_horizontaloffset = 7'h78;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S11_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S13_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S7_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S17_selected_tile;
          debug1 = 1'h1;
        end
      end
      S13_selected_tile: begin
        M_selector_horizontaloffset = 8'hf0;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S12_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S14_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S8_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S18_selected_tile;
          debug1 = 1'h1;
        end
      end
      S14_selected_tile: begin
        M_selector_horizontaloffset = 9'h168;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S13_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S15_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S9_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S19_selected_tile;
          debug1 = 1'h1;
        end
      end
      S15_selected_tile: begin
        M_selector_horizontaloffset = 9'h1e0;
        M_selector_verticaloffset = 7'h68;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S14_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S16_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S10_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S20_selected_tile;
          debug1 = 1'h1;
        end
      end
      S16_selected_tile: begin
        M_selector_horizontaloffset = 6'h3c;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S15_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S17_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S11_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S21_selected_tile;
          debug1 = 1'h1;
        end
      end
      S17_selected_tile: begin
        M_selector_horizontaloffset = 8'hb4;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S16_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S18_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S12_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S22_selected_tile;
          debug1 = 1'h1;
        end
      end
      S18_selected_tile: begin
        M_selector_horizontaloffset = 9'h12c;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S17_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S19_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S13_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S23_selected_tile;
          debug1 = 1'h1;
        end
      end
      S19_selected_tile: begin
        M_selector_horizontaloffset = 9'h1a4;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S18_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S20_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S14_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S24_selected_tile;
          debug1 = 1'h1;
        end
      end
      S20_selected_tile: begin
        M_selector_horizontaloffset = 10'h21c;
        M_selector_verticaloffset = 8'h9c;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S19_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S21_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S15_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S25_selected_tile;
          debug1 = 1'h1;
        end
      end
      S21_selected_tile: begin
        M_selector_horizontaloffset = 1'h0;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S20_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S22_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S16_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S1_selected_tile;
          debug1 = 1'h1;
        end
      end
      S22_selected_tile: begin
        M_selector_horizontaloffset = 7'h78;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S21_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S23_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S17_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S2_selected_tile;
          debug1 = 1'h1;
        end
      end
      S23_selected_tile: begin
        M_selector_horizontaloffset = 8'hf0;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S22_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S24_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S18_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S3_selected_tile;
          debug1 = 1'h1;
        end
      end
      S24_selected_tile: begin
        M_selector_horizontaloffset = 9'h168;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S23_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S25_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S19_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S4_selected_tile;
          debug1 = 1'h1;
        end
      end
      S25_selected_tile: begin
        M_selector_horizontaloffset = 9'h1e0;
        M_selector_verticaloffset = 8'hd0;
        if (center) begin
          
        end
        if (left & M_counter_inc_state) begin
          M_selected_tile_d = S24_selected_tile;
          debug1 = 1'h1;
        end
        if (right & M_counter_inc_state) begin
          M_selected_tile_d = S1_selected_tile;
          debug1 = 1'h1;
        end
        if (up & M_counter_inc_state) begin
          M_selected_tile_d = S20_selected_tile;
          debug1 = 1'h1;
        end
        if (down & M_counter_inc_state) begin
          M_selected_tile_d = S5_selected_tile;
          debug1 = 1'h1;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_tile1_orientation_q <= M_tile1_orientation_d;
    M_selected_tile_q <= M_selected_tile_d;
  end
  
endmodule
