/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module hsync_buffer_counter_4 (
    input clk,
    output reg [4:0] hsync_reload_count
  );
  
  
  
  reg [27:0] M_render_counter_d, M_render_counter_q = 1'h0;
  
  wire [1-1:0] M_hvsync_vga_h_sync;
  wire [1-1:0] M_hvsync_vga_v_sync;
  wire [1-1:0] M_hvsync_inDisplayArea;
  wire [11-1:0] M_hvsync_CounterX;
  wire [9-1:0] M_hvsync_CounterY;
  hvsync_generator_1 hvsync (
    .clk(clk),
    .vga_h_sync(M_hvsync_vga_h_sync),
    .vga_v_sync(M_hvsync_vga_v_sync),
    .inDisplayArea(M_hvsync_inDisplayArea),
    .CounterX(M_hvsync_CounterX),
    .CounterY(M_hvsync_CounterY)
  );
  
  always @* begin
    M_render_counter_d = M_render_counter_q;
    
    hsync_reload_count = 1'h0;
    M_render_counter_d = M_render_counter_q + 1'h1;
    if (M_render_counter_q < 5'h19) begin
      hsync_reload_count = M_render_counter_q + 1'h1;
    end
    if (M_hvsync_vga_h_sync) begin
      M_render_counter_d = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    M_render_counter_q <= M_render_counter_d;
  end
  
endmodule
